import { NextRequest, NextResponse } from "next/server";
import { requireUser } from "@/lib/privy";
import { supabase } from "@/lib/supabase";
import { verifyInviteToken } from "@/lib/invite";

export async function POST(req: NextRequest) {
  const token = req.headers.get("authorization")?.replace("Bearer ", "");
  if (!token) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const user = await requireUser(token).catch(() => null);
  if (!user) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const { invite_token, bet_id } = await req.json();

  if (!invite_token) return NextResponse.json({ error: "invite_token required" }, { status: 400 });

  // Look up event by token
  const { data: event } = await supabase
    .from("events")
    .select("id, name, ends_at, invite_token")
    .eq("invite_token", invite_token)
    .single();

  if (!event) return NextResponse.json({ error: "invalid invite link" }, { status: 404 });

  // Verify HMAC — ensures the token was generated by us, not guessed
  if (!verifyInviteToken(event.id, invite_token)) {
    return NextResponse.json({ error: "invalid invite link" }, { status: 404 });
  }

  const { error: joinError } = await supabase
    .from("event_guests")
    .upsert({ event_id: event.id, user_id: user.userId }, { onConflict: "event_id,user_id", ignoreDuplicates: true });

  if (joinError) return NextResponse.json({ error: joinError.message }, { status: 500 });

  if (bet_id) {
    const { error: inviteError } = await supabase
      .from("bet_invites")
      .upsert({ bet_id, user_id: user.userId }, { onConflict: "bet_id,user_id", ignoreDuplicates: true });
    if (inviteError) console.error("bet_invites upsert failed:", inviteError.message);
  }

  return NextResponse.json({ eventId: event.id, eventName: event.name });
}

// Public: fetch event preview by invite token (no auth required)
export async function GET(req: NextRequest) {
  const invite_token = req.nextUrl.searchParams.get("token");

  if (!invite_token) return NextResponse.json({ error: "token required" }, { status: 400 });

  const { data: event } = await supabase
    .from("events")
    .select("id, name, ends_at")
    .eq("invite_token", invite_token)
    .single();

  if (!event) return NextResponse.json({ error: "not found" }, { status: 404 });

  if (!verifyInviteToken(event.id, invite_token)) {
    return NextResponse.json({ error: "not found" }, { status: 404 });
  }

  const { count } = await supabase
    .from("event_guests")
    .select("*", { count: "exact", head: true })
    .eq("event_id", event.id);

  return NextResponse.json({ event: { ...event, guest_count: count ?? 0 } });
}
